### ISSUE TITLE
Incorrectly handled revoked token validation

### ISSUE THREAD

**Issue by oivinds** [aamplugin/advanced-access-manager#238]
I am still able to refresh token in browser A, after I log in on browser B.  So "One Session Per User" seems not to work.

I have set authentication.jwt.registryLimit = 1, but I can log in to more than 1 browsers at a time.

**Comment by aamplugin** [comment]
Hello @oivinds,

I believe there is a slight confusion with how this particular functionality works. So let me unpack it for you.

The "One Session Per User" has nothing to do with `registryLimit` and only checks if there are any other active sessions for current user. 
<img width="1263" alt="Screen Shot 2022-12-19 at 10 34 20 AM" src="https://user-images.githubusercontent.com/34006503/208462628-f166b687-5118-4c48-a190-0c85e2733147.png">

It uses WordPress core function `WP_Session_Tokens::get_instance` for this purpose. I can't speak about reliability for this function, but in our testing through the years, we did not find any noticeable issues, expect in rare cases when it did not pick up the correct number of sessions if authentication was happening back-to-back from different locations.

The `registryLimit` setting tell AAM how many tokens to store internally per user. In your case, one one token will be stored internally and displayed on the UI.

<img width="802" alt="Screen Shot 2022-12-19 at 12 12 38 PM" src="https://user-images.githubusercontent.com/34006503/208481845-a4998d64-aec8-4cb1-a693-faa8312249dd.png">

However, I must admit, that **there is an issue** with properly validating revoked tokens in some instances. I was able to reproduce the issue and the fix is coming tonight with new release.

Thank you for the feedback.
Regards,
Vasyl
