### ISSUE TITLE
Restoring a previous Policy Revision adds backslashes

### ISSUE THREAD

**Issue by solaceten** [aamplugin/advanced-access-manager#294]
If I restore a previous version of a policy, using the WordPress Revision history, it adds heaps of backslashes that makes the JSON invalid and I have to manually remove them all....

**Comment by aamplugin** [comment]
Thank  you @solaceten for the report. I can confirm that the issue is reproducible and we are going to fix it in the upcoming release.

<img width="1269" alt="Screen Shot 2023-07-09 at 9 18 33 PM" src="https://github.com/aamplugin/advanced-access-manager/assets/34006503/480bac62-947a-45ef-9e1d-ed12ad4d1943">
