### ISSUE TITLE
HomePage set in WP options is able to be deleted, despite deny delete_others_pages

### ISSUE THREAD

**Issue by solaceten** [aamplugin/advanced-access-manager#295]
In Reading Settings (wp-admin/options-reading.php) I set the HomePage  (author is admin)

In AAM capabilities, I set Editor as "delete_others_pages" denied (unticked).  Now - all pages made by admin cannot be deleted by editor, except the Homepage which can, but I don't want to allow this.

Is it a bug ?

**Comment by aamplugin** [comment]
Hello @solaceten,

Great question and looks like you uncovered bug in WordPress core. The issue is in the `/wp-includes/capabilities.php` file. Lines 156-164:

<img width="823" alt="Screen Shot 2023-07-25 at 10 12 52 PM" src="https://github.com/aamplugin/advanced-access-manager/assets/34006503/e15468dd-7c85-4b78-a741-98432de195b4">

In short, you need to uncheck also `delete_published_posts` capabilities.
